baseURL = "https://allen-r-chan-portfolio.netlify.app"
languageCode = "en-us"
title = "Allen R Chan | Director of Engineering"
# theme = "timer-hugo"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "#about"
weight = 2

[[menu.main]]
name = "Top Skills"
url = "#skills"
weight = 3

[[menu.main]]
name = "Gallery"
url = "/"
weight = 4

[[menu.main]]
name = "Blog"
url = "/"
weight = 5


[[menu.main]]
name = "Contact"
url = "contact/"
weight = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Timer Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "images/slider.jpg"
heading = "HI, MY NAME IS ALLEN R CHAN"
description = "I build businesses on trust, transparency, and delivering results. With over 20 years of experience, I help organizations solve complex challenges, align engineering strategies with business goals, and stay ahead of market trends to deliver lasting value."
# button
btn = true
btnText = "See More"
btnURL = "#about"

# flip text
[[params.banner.flipText]]
title = "I AM A DIRECTOR OF ENGINEERING"
[[params.banner.flipText]]
title = "I AM A PMP TECHNICAL PROGRAM MANAGER"
[[params.banner.flipText]]
title = "I AM A CSM SCRUM MASTER"

# Homepage About Section
[params.about]
enable = true
title = "ABOUT ME"
content = ""
image = "images/about/about.jpg"

# Homepage SKills Section
[params.skills]
enable = true
title = "MY SKILLS"

# Call to Action
[params.cta]
enable = true
title = "SO WHAT YOU THINK ?"
content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
btnText = "Connect with me"
btnURL = "/#contact-section"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "Latest Works"
subtitle = "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/allenrchan/"

[[params.socialIcon]]
icon = "fab fa-flickr"
url = "https://www.flickr.com/photos/vividvoyager/"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/in/allenchan/"
